version: "3"

services:
  web:
    container_name: web_container
    build: .
    ports:
      - 8082:80
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root

  db:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=gestion_produits
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
  
  minio:
    container_name: minio_container
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey
    ports:
      - "9001:9000"
    command: server /export