version: "3"

services:
  web:
    container_name: web_container
    build: .
    ports:
      - 8082:80
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db

  db:
    container_name: mysql_container
    image: mysql:5.7
    volumes:
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: gestion_produits
      MYSQL_ROOT_PASSWORD: root