version: "3"

services:
  web:
    container_name: web_container
    build: .
    ports:
      - 8082:80
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: root

  db:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=gestion_produits
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/